// This file is auto-generated. Do not edit directly.
// Generated on 2025-08-12T16:41:06.478Z

/**
 * Embedded context content for each program
 * This avoids having to load context files at runtime
 */
export const embeddedContexts: Record<string, string> = {
  'skyfielders-python-skyfield': "No context files defined for skyfielders-python-skyfield",
  'dstndstn-astrometry-net': "No context files defined for dstndstn-astrometry-net",
  'astropy-astroquery': "No context files defined for astropy-astroquery",
  'einsteinpy-einsteinpy': "No context files defined for einsteinpy-einsteinpy",
  'lightkurve-lightkurve': "No context files defined for lightkurve-lightkurve",
  'gwpy-gwpy': "No context files defined for gwpy-gwpy",
  'gwastro-pycbc': "No context files defined for gwastro-pycbc",
  'amrex-astro-castro': "No context files defined for amrex-astro-castro",
  'healpy-healpy': "No context files defined for healpy-healpy",
  'astropy-photutils': "No context files defined for astropy-photutils",
  'lesgourg-class-public': "No context files defined for lesgourg-class-public",
  'spacepy-spacepy': "No context files defined for spacepy-spacepy",
  'scottransom-presto': "No context files defined for scottransom-presto",
  'galsim-developers-galsim': "No context files defined for galsim-developers-galsim",
  'jobovy-galpy': "No context files defined for jobovy-galpy",
  'radis-radis': "No context files defined for radis-radis",
  'spacetelescope-poppy': "No context files defined for spacetelescope-poppy",
  'minaskar-zeus': "No context files defined for minaskar-zeus",
  'tardis-sn-tardis': "No context files defined for tardis-sn-tardis",
  'astropy-astroplan': "No context files defined for astropy-astroplan",
  'johannesbuchner-pymultinest': "No context files defined for johannesbuchner-pymultinest",
  'henrysky-astronn': "No context files defined for henrysky-astronn",
  'sep-developers-sep': "No context files defined for sep-developers-sep",
  'astro-informatics-s2fft': "No context files defined for astro-informatics-s2fft",
  'stingraysoftware-stingray': "No context files defined for stingraysoftware-stingray",
  'johannesbuchner-ultranest': "No context files defined for johannesbuchner-ultranest",
  'astropy-specutils': "No context files defined for astropy-specutils",
  'mperrin-poppy': "No context files defined for mperrin-poppy",
  'pypeit-pypeit': "No context files defined for pypeit-pypeit",
  'sczesla-pyastronomy': "No context files defined for sczesla-pyastronomy",
  'cmbant-getdist': "No context files defined for cmbant-getdist",
  'quatrope-astroalign': "No context files defined for quatrope-astroalign",
  'polymathicai-astroclip': "No context files defined for polymathicai-astroclip",
  'adrn-gala': "No context files defined for adrn-gala",
  'deepsphere-deepsphere-cosmo-tf1': "No context files defined for deepsphere-deepsphere-cosmo-tf1",
  'skypyproject-skypy': "No context files defined for skypyproject-skypy",
  'astropy-reproject': "No context files defined for astropy-reproject",
  'astropy-halotools': "No context files defined for astropy-halotools",
  'galacticdynamics-oxford-agama': "No context files defined for galacticdynamics-oxford-agama",
  'lwang-astro-petar': "No context files defined for lwang-astro-petar",
  'michellelochner-astronomaly': "No context files defined for michellelochner-astronomaly",
  'radio-astro-tools-spectral-cube': "No context files defined for radio-astro-tools-spectral-cube",
  'amrex-astro-nyx': "No context files defined for amrex-astro-nyx",
  'autostronomy-astrophot': "No context files defined for autostronomy-astrophot",
  'radioastronomysoftwaregroup-pyuvdata': "No context files defined for radioastronomysoftwaregroup-pyuvdata",
  'astropy-ccdproc': "No context files defined for astropy-ccdproc",
  'astroml-gatspy': "No context files defined for astroml-gatspy",
  'astrocv-astrocv': "No context files defined for astrocv-astrocv",
  'spacetelescope-astronify': "No context files defined for spacetelescope-astronify",
  'astrorama-sourcextractorplusplus': "No context files defined for astrorama-sourcextractorplusplus",
  'astropy-pyvo': "No context files defined for astropy-pyvo",
  'astropy-astroscrappy': "No context files defined for astropy-astroscrappy",
  'sncosmo-sncosmo': "No context files defined for sncosmo-sncosmo",
  'alessiospuriomancini-cosmopower': "No context files defined for alessiospuriomancini-cosmopower",
  'astro-informatics-harmonic': "No context files defined for astro-informatics-harmonic",
  'astropy-spisea': "No context files defined for astropy-spisea",
  'astroua-turbustat': "No context files defined for astroua-turbustat",
  'pynucastro-pynucastro': "No context files defined for pynucastro-pynucastro",
  'artificialstellarpopulations-artpop': "No context files defined for artificialstellarpopulations-artpop",
  'cmateu-galstreams': "No context files defined for cmateu-galstreams",
  'smith42-astroddpm': "No context files defined for smith42-astroddpm",
  'astrosmili-smili': "No context files defined for astrosmili-smili",
  'lofar-astron-pybdsf': "No context files defined for lofar-astron-pybdsf",
  'stellar-group-octotiger': "No context files defined for stellar-group-octotiger",
  'simonsobs-pixell': "No context files defined for simonsobs-pixell",
  'quokka-astro-quokka': "No context files defined for quokka-astro-quokka",
  'dartoon-galight': "No context files defined for dartoon-galight",
  'threeml-astromodels': "No context files defined for threeml-astromodels",
  'pmelchior-skymapper': "No context files defined for pmelchior-skymapper",
  'astroaccelerateorg-astro-accelerate': "No context files defined for astroaccelerateorg-astro-accelerate",
  'roban-cosmolopy': "No context files defined for roban-cosmolopy",
  'sncosmo-extinction': "No context files defined for sncosmo-extinction",
  'cosmostatgw-gwfast': "No context files defined for cosmostatgw-gwfast",
  'zoglauer-megalib': "No context files defined for zoglauer-megalib",
  'cosmolattice-cosmolattice': "No context files defined for cosmolattice-cosmolattice",
  'dendrograms-astrodendro': "No context files defined for dendrograms-astrodendro",
  'hpc4cmb-toast': "No context files defined for hpc4cmb-toast",
  'numcosmo-numcosmo': "No context files defined for numcosmo-numcosmo",
  'amrex-astro-maestroex': "No context files defined for amrex-astro-maestroex",
  'punzo-slicerastro': "No context files defined for punzo-slicerastro",
  'astrocatalogs-astrocats': "No context files defined for astrocatalogs-astrocats",
  'astromatic-swarp': "No context files defined for astromatic-swarp",
  'astromatic-visiomatic': "No context files defined for astromatic-visiomatic",
  'elisej-astroabc': "No context files defined for elisej-astroabc",
  'daniel-muthukrishna-astrodash': "No context files defined for daniel-muthukrishna-astrodash",
  'nuclear-multimessenger-astronomy-nmma': "No context files defined for nuclear-multimessenger-astronomy-nmma",
  'clwainwright-cosmotransitions': "No context files defined for clwainwright-cosmotransitions",
  'galacticusorg-galacticus': "No context files defined for galacticusorg-galacticus",
  'yuliang419-astronet-triage': "No context files defined for yuliang419-astronet-triage",
  'dsavransky-exosims': "No context files defined for dsavransky-exosims",
  'smith42-astropt': "No context files defined for smith42-astropt",
  'amrex-astro-maestro': "No context files defined for amrex-astro-maestro",
  'dalya-weirdestgalaxies': "No context files defined for dalya-weirdestgalaxies",
  'mtazzari-galario': "No context files defined for mtazzari-galario",
  'cosmodesi-pycorr': "No context files defined for cosmodesi-pycorr",
  'lofar-astron-rmextract': "No context files defined for lofar-astron-rmextract",
  'trasal-frbpoppy': "No context files defined for trasal-frbpoppy",
  'astro-group-bristol-gradus-jl': "No context files defined for astro-group-bristol-gradus-jl",
  'astro-sean-autophot': "No context files defined for astro-sean-autophot",
  'spacetelescope-astrocut': "No context files defined for spacetelescope-astrocut",
  'quantopian-zipline': "No context files defined for quantopian-zipline",
  'mlfinlab-mlfinlab': "No context files defined for mlfinlab-mlfinlab",
  'ranaroussi-yfinance': "No context files defined for ranaroussi-yfinance",
  'pmorissette-ffn': "No context files defined for pmorissette-ffn",
  'quantopian-pyfolio': "No context files defined for quantopian-pyfolio",
  'fmilthaler-finquant': "No context files defined for fmilthaler-finquant",
  'jamesmawm-high-frequency-trading-model-with-ib': "No context files defined for jamesmawm-high-frequency-trading-model-with-ib",
  'quantopian-empyrical': "No context files defined for quantopian-empyrical",
  'quantopian-alphalens': "No context files defined for quantopian-alphalens",
  'quantopian-qgrid': "No context files defined for quantopian-qgrid",
};

/**
 * Get the embedded context for a program
 * @param programId The ID of the program
 * @returns The embedded context content or undefined if not found
 */
export function getEmbeddedContext(programId: string): string | undefined {
  return embeddedContexts[programId];
}
